channels:
  - id: UCXuqSBlHAE6Xw-yeJA0Tunw
    name: Linus Tech Tips
    frequency_hours: 24
    priority: 1
    active: true
    include_comments: false
    
  - id: UC4w1YQAJMWOz4qtxinq55LQ
    name: MKBHD
    frequency_hours: 24
    priority: 1
    active: true
    include_comments: false
  
  - id: UCuMJPFqazQI4SofSFEd-5zA
    name: Cô Ngân TV
    frequency_hours: 12
    priority: 2
    active: true
    include_comments: true
    
  - id: UCJ0-OtVpF0SU9F3RVKz__bg
    name: Duy Thanh Nguyễn
    frequency_hours: 24
    priority: 1
    active: true
    include_comments: false

settings:
  max_videos_per_channel: 50
  max_comments_per_video: 100
  batch_size: 10
  retry_failed_after_hours: 1
  api_delay_seconds: 0.5
