name: 'yt_analytics_pipeline'
version: '1.0.0'
config-version: 2

profile: 'yt_analytics_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  yt_analytics_pipeline:
    staging:
      +materialized: view
      +schema: staging
      +tags: ['staging']

    intermediate:
      +materialized: view
      +schema: intermediate
      +tags: ['intermediate']

    mart:
      +materialized: table
      +schema: mart
      +tags: ['mart', 'production']

      fct_video_performance:
        +materialized: table
        +partition_by:
          field: published_date
          data_type: date
          granularity: day
        +cluster_by: ['channel_id', 'category_id']

      agg_daily_metrics:
        +materialized: table
        +partition_by:
          field: metric_date
          data_type: date
          granularity: day
        +cluster_by: ['channel_id']

vars:
  youtube_raw_database: "{{ env_var('GCP_PROJECT_ID') }}"
  youtube_raw_schema: "{{ env_var('BQ_DATASET_ID', 'raw_yt') }}"

  youtube__video_passthrough_columns: []
  youtube__channel_passthrough_columns: []

  youtube__using_multiple_sources: false
  youtube__union_schemas: []

seeds:
  yt_analytics_pipeline:
    +schema: seeds
    youtube_categories:
      +column_types:
        category_id: string
        category_name: string
        description: string

tests:
  yt_analytics_pipeline:
    +store_failures: true
    +schema: test_failures

require-dbt-version: [">=1.5.0", "<2.0.0"]