version: 2

sources:
  - name: youtube_raw
    description: |
      Raw JSON data from YouTube Data API v3 stored in BigQuery.
      Data is synced by Python crawler (extract/crawlers.py).
      
      **Sync frequency:** Configured per channel in channels.yml (default: daily)
      **Data format:** JSON/STRUCT columns containing full API responses
      **Storage:** BigQuery dataset specified by BQ_DATASET_ID env var
    
    database: "{{ env_var('GCP_PROJECT_ID') }}"
    schema: "{{ env_var('BQ_DATASET_ID', 'raw_yt') }}"
    
    freshness:
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    
    loaded_at_field: _crawled_at
    
    tables:
      - name: youtube_videos_raw
        description: |
          Raw video data from YouTube Data API v3 videos.list() endpoint.
          Each row contains full JSON response in 'data' column.
        
        columns:
          - name: id
            description: Video ID (Primary Key)
            tests:
              - unique
              - not_null
          
          - name: channel_id
            description: Channel ID (denormalized for filtering)
            tests:
              - not_null
          
          - name: data
            description: |
              STRUCT/JSON column containing full API response with:
              - data.snippet: title, description, tags, publishedAt, categoryId
              - data.statistics: viewCount, likeCount, commentCount
              - data.contentDetails: duration (ISO 8601), caption, definition
              - data.status: privacyStatus, embeddable, madeForKids
          
          - name: _crawled_at
            description: Timestamp when data was crawled
            tests:
              - not_null

      - name: youtube_channels_raw
        description: |
          Raw channel data from YouTube Data API v3 channels.list() endpoint.
        
        columns:
          - name: id
            description: Channel ID (Primary Key)
            tests:
              - unique
              - not_null
          
          - name: data
            description: |
              STRUCT/JSON column containing:
              - data.snippet: title, publishedAt, country
              - data.statistics: subscriberCount, viewCount, videoCount
              - data.contentDetails.relatedPlaylists.uploads: Uploads playlist ID
              - data.topicDetails.topicIds: Topic categorization
          
          - name: _crawled_at
            description: Timestamp when data was crawled
            tests:
              - not_null

      - name: youtube_playlists_raw
        description: |
          Raw playlist data from YouTube Data API v3 playlists.list() endpoint.
        
        columns:
          - name: id
            description: Playlist ID (Primary Key)
            tests:
              - unique
              - not_null
          
          - name: channel_id
            description: Channel ID that owns the playlist
            tests:
              - not_null
          
          - name: data
            description: |
              STRUCT/JSON column containing:
              - data.snippet: title, publishedAt
              - data.contentDetails.itemCount: Number of videos
              - data.status.privacyStatus: public/private/unlisted
          
          - name: _crawled_at
            description: Timestamp when data was crawled
            tests:
              - not_null

      - name: youtube_comments_raw
        description: |
          Raw comments data from YouTube Data API v3 commentThreads.list() endpoint.
          Only present if include_comments=true in channels.yml
        
        columns:
          - name: id
            description: Comment thread ID (Primary Key)
            tests:
              - unique
              - not_null
          
          - name: video_id
            description: Video ID the comment belongs to
            tests:
              - not_null
          
          - name: channel_id
            description: Channel ID (for filtering)
            tests:
              - not_null
          
          - name: data
            description: |
              STRUCT/JSON column containing:
              - data.snippet.topLevelComment.snippet: authorDisplayName, textDisplay, likeCount, publishedAt
              - data.snippet.totalReplyCount: Number of replies
          
          - name: _crawled_at
            description: Timestamp when data was crawled
            tests:
              - not_null
